### ISSUE TITLE
Can't export to onnx

### ISSUE THREAD

**Issue by VitalyVaryvdin** [ankandrew/fast-plate-ocr#12]
Hi,

I've trained the model on custom dataset and trying to export to onnx, but getting the following errors:

```
Not equal to tolerance rtol=1e-05, atol=0

Mismatched elements: 215 / 216 (99.5%)
Max absolute difference: 0.00083357
Max relative difference: 0.00325669
 x: array([[0.016661, 0.016661, 0.016661, 0.016661, 0.016661, 0.016661,
        0.016661, 0.016661, 0.016661, 0.016661, 0.058114, 0.03646 ,
        0.10078 , 0.161502, 0.026042, 0.051265, 0.028406, 0.034214,...
 y: array([[0.016673, 0.016673, 0.016673, 0.016673, 0.016673, 0.016673,
        0.016673, 0.016673, 0.016673, 0.016673, 0.058155, 0.036436,
        0.100745, 0.161467, 0.026064, 0.051226, 0.028396, 0.034214,...
```

Export command: `fast_plate_ocr export-onnx --model trained-models/2024-04-28_19-03-07/cnn_ocr-epoch_520-acc_1.000.keras --output-path lpr.onnx --opset 18 --config-file config.yaml`

Training command:
```
KERAS_BACKEND=tensorflow fast_plate_ocr train \
    --annotations ../datasets/ria/annotation_fast_train.csv \
    --val-annotations ../datasets/ria/annotation_fast_valid.csv \
    --batch-size 128 \
    --epochs 750 \
    --dense \
    --early-stopping-patience 100 \
    --reduce-lr-patience 50 \
    --config-file config.yaml
```

config:
```
max_plate_slots: 9
alphabet: '0123456789ABEKMHOPCTYXD_'
pad_char: '_'
img_height: 70
img_width: 140
```

Would love any help

upd: I probably was too fast to open the issue. Apparently, model was exported successfully, just their predictions are a little bit different.

That output should probably be rephrased to better indicate the case?

**Comment by ankandrew** [comment]
Hi there! Yep, I agree that behavior here is not very clear. Will improve the message, thanks! 🙏

**Comment by VitalyVaryvdin** [comment]
That was fast. Thanks a lot!

Love the model so far, sub ms inference time on TRT is awesome

Closing the issue
