### ISSUE TITLE
Readme / Doc not clear 

### ISSUE THREAD

**Issue by DamienChabret** [ankandrew/fast-plate-ocr#16]
I am trying to follow your guide for custom training and custom validation. For example, when you explain how to train, you don't specify the file type for the config.yml file, and you don't mention that the training script must be executed from the command line. It would be helpful if you could explain or indicate every type of argument for better comprehension.

In the model validation section, you provide the command but don't explain what benchmark/annotation.csv is (if you can explain to me, because I don't know). I think it would be helpful to give more detailed explanations in the same section, to avoid having to search for information in different places. This would make the guide easier to follow.

(And explain the utilities of the commands, maybe give a project example of custom training)

**Comment by ankandrew** [comment]
Thanks for the feedback. Will add some more details to docs.
