### ISSUE TITLE
Europeen Plate

### ISSUE THREAD

**Issue by TsRun** [ankandrew/fast-plate-ocr#23]
I rlly liked ur project, very hard to find this type of thing in local and as precise as yours, i wanted to use this for european plates, howerver i need to detect the country of the plate as well, do u think i can add this easily ? And do u think u can give access to the European training dataset ? Thank ur in advance for ur answer

**Comment by ankandrew** [comment]
Hi! Great you find this project helpful 🚀!

1. Regarding country classification: I guess this is possible, I can add a new head to classify countries. I don't have enough bandwidth do this atm. My current dataset for Europe plates has some challenging plates, and I think that model may struggle to retrieve country info given that is denoted usually by very small letters at bottom left. 

2. At some point I'll probably publish the train dataset.

**Comment by ankandrew** [comment]
Some time after, I'm releasing soon some pre-trained models trained with more data and w/ region recognition (region for now at country level). See #70.

**Comment by ankandrew** [comment]
New CCT v2 models are trained to recognized from a bunch of European countries. Better late than never :)
