### ISSUE TITLE
Converting ONNX to MLModel in 2024

### ISSUE THREAD

**Issue by BasistaMatej** [ankandrew/fast-plate-ocr#24]
First of all, thank you for your amazing work on Fast Plate OCR! It’s an excellent and highly valuable project, and I’m enjoying exploring it.

I’ve run into an issue regarding converting models to Core ML format. Specifically, I’m trying to create an MLModel from either the ONNX file or a .keras file. However, it seems that the following function is no longer supported in 2024:
`coremltools.converters.onnx.convert(...)`

Could you please help clarify the following:

1. Is there a new approach or method for converting an ONNX file to an MLModel using coremltools or another library?
2. If ONNX is not directly convertible anymore, would it be feasible to first convert .keras to Core ML? Any guidance here would be greatly appreciated.

Thanks in advance for your help and for this wonderful project! Looking forward to your insights. 🙏

**Comment by ankandrew** [comment]
Hi, for all models I provide the trained Keras model (i.e. useful if you want to fine-tune). You can use those `.keras` models to try to convert them to CoreML. Maybe try something like

```python
import coremltools as ct

from fast_plate_ocr.train.utilities.utils import load_keras_model

keras_model_path = "./european_mobile_vit_v2_ocr.keras"
model = load_keras_model(
    model_path=keras_model_path,
    vocab_size=37,
    max_plate_slots=7,
)
mlmodel = ct.convert(model, source="tensorflow", convert_to="mlprogram")
mlmodel.save("tmp.mlpackage")
```

**Comment by BasistaMatej** [comment]
Hi @ankandrew,

Thank you for your guidance and the amazing resources provided with Fast Plate OCR! However, I’m running into compatibility issues while trying to convert the Keras model to Core ML on my setup. Here are the details of my environment and the issue:

- **Python** 3.10.8
- **Tensorflow** 2.16.2 (tensorflow-macos tried too)
- **Machine** Macbook with Apple Silicon chip

TensorFlow 2.12.0 seems to be the most recent version tested with coremltools, but I encountered the following warning and error:

**Warning:**
`TensorFlow version 2.16.2 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.12.0 is the most recent version that has been tested.`

**Error**
`AttributeError: 'Functional' object has no attribute '_get_save_spec'. Did you mean: '_set_save_spec'?`


The error appears to arise during the conversion process when invoking ct.convert. It seems like an underlying incompatibility between the TensorFlow/Keras version and the Apple Silicon environment.

Tensorflow 2.12.0 is not compatibile with Apple Silicon.

1. If converting .keras files to Core ML is problematic, would you suggest trying to export the model to ONNX first and then to Core ML, or is there another proven pathway?
2. Are there any adjustments I can make to the load_keras_model or Core ML conversion call to avoid this _get_save_spec issue?

Thank you for your support and for this excellent project. Any guidance you can provide to help resolve these issues would be greatly appreciated.

**Comment by ankandrew** [comment]
The advantage of using ONNX models is that it already provides CoreML accelerator, so I always prefer to use that when possible, see https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html. I don't believe the problem is the `load_keras_model` utility function, it's really just a wrapper of:

```python
import keras

keras.models.load_model(...)
```

This issue I think it might more related to CoreML itself, I'd try rising an issue there.
